name: Build Cloak Shared Libraries

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NDK_VERSION: r25c
      GO_VERSION: "1.21.1"

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4

      - name: Checkout Cloak repository
        uses: actions/checkout@v4
        with:
          repository: cbeuw/Cloak
          ref: master
          path: CloakSrc

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Download and set up Android NDK
        run: |
          echo "Downloading Android NDK..."
          NDK_VERSION=${{ env.NDK_VERSION }}
          wget https://dl.google.com/android/repository/android-ndk-$NDK_VERSION-linux.zip -O android-ndk.zip
          unzip -q android-ndk.zip -d $HOME
          echo "ANDROID_NDK_HOME=$HOME/android-ndk-$NDK_VERSION" >> $GITHUB_ENV
          echo "$HOME/android-ndk-$NDK_VERSION/toolchains/llvm/prebuilt/linux-x86_64/bin" >> $GITHUB_PATH

      - name: Verify Go files location
        run: |
          ls -R CloakSrc # Display the directory structure to confirm Go files location

      - name: Build Cloak for arm64-v8a
        working-directory: CloakSrc # Adjust this path if needed
        env:
          CC: aarch64-linux-android21-clang
          GOOS: android
          GOARCH: arm64
          CGO_ENABLED: 1
        run: |
          mkdir -p ../build/arm64-v8a
          go build -buildmode=c-shared -o ../build/arm64-v8a/libcloak.so

      - name: Build Cloak for armeabi-v7a
        working-directory: CloakSrc # Adjust this path if needed
        env:
          CC: armv7a-linux-androideabi21-clang
          GOOS: android
          GOARCH: arm
          CGO_ENABLED: 1
        run: |
          mkdir -p ../build/armeabi-v7a
          go build -buildmode=c-shared -o ../build/armeabi-v7a/libcloak.so

      - name: Build Cloak for x86
        working-directory: CloakSrc # Adjust this path if needed
        env:
          CC: i686-linux-android21-clang
          GOOS: android
          GOARCH: 386
          CGO_ENABLED: 1
        run: |
          mkdir -p ../build/x86
          go build -buildmode=c-shared -o ../build/x86/libcloak.so

      - name: Build Cloak for x86_64
        working-directory: CloakSrc # Adjust this path if needed
        env:
          CC: x86_64-linux-android21-clang
          GOOS: android
          GOARCH: amd64
          CGO_ENABLED: 1
        run: |
          mkdir -p ../build/x86_64
          go build -buildmode=c-shared -o ../build/x86_64/libcloak.so

      - name: Upload Cloak shared libraries
        uses: actions/upload-artifact@v4
        with:
          name: cloak-shared-libraries
          path: build/
